name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        host: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.host }}
    env:
      TESTS_PATH: ./Tests
      CONFIGURATION: Release
      TESTS_CONFIGURATION: Debug
    steps:
    - name: Fix line endings
      run: git config --global core.autocrlf false
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Tests
      run: dotnet test ${{ env.TESTS_PATH }} -c ${{ env.TESTS_CONFIGURATION }} -p:PublishSingleFile=true
